### ISSUE TITLE
application/font-woff2 not compress to gzip

### ISSUE THREAD

**Issue by ngohungphuc** [IEvangelist/IEvangelist.AspNetCore.Optimization#1]
I try with `font-woff2` and the response is not using gzip. Other file is fine
```csharp
services.Configure<GzipCompressionProviderOptions>(
    options => options.Level = System.IO.Compression.CompressionLevel.Optimal);
services.AddResponseCompression(options =>
{
    options.MimeTypes = new[]
    {
         // Default
        "text/plain",
        "text/css",
        "application/javascript",
        "text/html",
        "application/xml",
        "text/xml",
        "application/json",
        "text/json",
        // Custom
        "image/svg+xml",
        "application/font-woff2",
        "application/font-woff",
        "application/font-ttf",
        "application/font-eot",
        "image/jpeg",
        "image/png"
    };
});
```

**Comment by IEvangelist** [comment]
Hi @ngohungphuc,

Are you able to look at the request from the browser an ensure that it is one of the correct MIME types? If it does in fact match one of the types in your list, I'm not really sure -- perhaps remove the line:
```csharp
services.Configure<GzipCompressionProviderOptions>(
    options => options.Level = System.IO.Compression.CompressionLevel.Optimal);
```

**Comment by ngohungphuc** [comment]
@IEvangelist here is my response
![chrome_2018-03-15_00-16-48](https://user-images.githubusercontent.com/13591213/37419086-49b7f700-27e6-11e8-96b6-2b73caaaeb62.png)

**Comment by IEvangelist** [comment]
@ngohungphuc please share your repo for this with me so that I can look into. I do not see that you have a fork of this repo, and I looked at your repos and I'm not seeing it there either.

**Comment by ngohungphuc** [comment]
@IEvangelist you can take a look at here 
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/master/src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs#L216-L242

**Comment by IEvangelist** [comment]
Thanks @ngohungphuc!

I looked at this and it seems correct. The order of the static file middle ware coming after the add compression invocation is correct. You're correctly adding compressing. I'm not really sure. I do have a few ideas, but it is hard to say.

There reason I was asking about seeing the request specifically, is that if the request does not accept compression - the response will not be compressed. See these lines here: https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionMiddleware.cs#L49-L53.

Could you please confirm this?

**Comment by ngohungphuc** [comment]
> The order of the static file middle ware coming after the add compression invocation is correct

I try to switch order between those 2 and still no success

**Comment by IEvangelist** [comment]
The order is correct. I want you to look at the request in the web dev tools and verify that the request does in fact accept gzip, if it does not then the response will __not__ gzip. Here is an example of what I am looking for:
![image](https://user-images.githubusercontent.com/7679720/37424123-b3c05a10-278d-11e8-9894-d8c08bf80cc0.png)

**Comment by ngohungphuc** [comment]
@IEvangelist Hi sorry for late reply. Been quite busy. As you can see the woff font is gzip and woff2 dont
![chrome_2018-03-15_21-30-15](https://user-images.githubusercontent.com/13591213/37469556-149a3f8a-2898-11e8-8261-87c6f63569d8.png)
![chrome_2018-03-15_21-30-24](https://user-images.githubusercontent.com/13591213/37469557-14e36cbe-2898-11e8-9431-e1093a04cfa7.png)

**Comment by IEvangelist** [comment]
@ngohungphuc bravo!
These were very helpful, I believe I have a fix for the issue: https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/pull/58

**Comment by ngohungphuc** [comment]
@IEvangelist much appreciate your help.

**Comment by ngohungphuc** [comment]
@IEvangelist I replace your code with `font/woff2` and is work fine maybe you made some typo
